apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: multi-server
          image: bes1815/multi-server
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: postgres-secret
