apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  selector:
    component: web
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: server-cluster-ip-service
spec:
  selector:
    component: server
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
spec:
  selector:
    component: redis
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-ip-service
spec:
  selector:
    component: postgres
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
